[custom.all.playground]
type = "local"
path = "."
ipkg = "test.ipkg"
test = "test/test.ipkg"

[custom.all.playground-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.finger-tree-example]
type = "local"
path = "examples/finger-tree"
ipkg = "finger-tree.ipkg"

[custom.all.push-pull-frp-example]
type = "local"
path = "examples/push-pull-frp"
ipkg = "push-pull-frp.ipkg"

[custom.all.red-black-tree-example]
type = "local"
path = "examples/red-black-tree"
ipkg = "red-black-tree.ipkg"
